import { NextResponse } from "next/server";

export async function GET(req) {
    const url = new URL(req.url);

    const accessToken = url.searchParams.get("access_token");

    if (!accessToken) {
        return NextResponse.json({ error: "Missing access_token" }, { status: 401 });
    }

    const userResponse = await fetch(
    `https://api.spotify.com/v1/me`,
        {
            headers: {
                Authorization: `Bearer ${accessToken}`
            }
        }
    );

    const userData = await userResponse.json();

    const playlistResponse = await fetch(`https://api.spotify.com/v1/users/${userData.id}/playlists`, {
        method: "POST",
        headers: {
            Authorization: `Bearer ${accessToken}`,
            "Content-Type": "application/json",
        },
        body: JSON.stringify({
            name: `STM-Playlist-${Date.now()}`,
            description: "A playlist generated by Spotify-Taste-Mixer",
            public: false
        })
    });

    const playlistData = await playlistResponse.json();

    return NextResponse.json(playlistData, { status: playlistResponse.status });
}